switch("path", "../src")
switch("path", "../../egison-patterns/src")
switch("path", "../../actor-state-machine/src")
switch("passC", "--coverage")
switch("passL", "--coverage")
switch("define", "rteffectsTesting")
